### ISSUE TITLE
Gateway "bitbag_imoje" does not exist

### ISSUE THREAD

**Issue by orzeszki** [BitBagCommerce/SyliusIngPlugin#72]
**Plugin version: 2.0.0 and 1.0.2
Sylius version: 1.11.14**

I've added new payment by Sylius Admin Panel:
**Type:** BitBag_imoje
**Code:** tried imoje, ing, bitbag_imoje
**All required fields are filled**
Done every steps from here: [https://github.com/BitBagCommerce/SyliusIngPlugin/blob/HEAD/doc/installation.md](url)

But during redirection from checkout process where I chose available ing payment I get this error:

```
Payum\Core\Exception\InvalidArgumentException:
Gateway "bitbag_imoje" does not exist.

  at vendor/payum/payum/src/Payum/Core/Registry/AbstractRegistry.php:98
  at Payum\Core\Registry\AbstractRegistry->getGateway('bitbag_imoje')
     (vendor/payum/payum/src/Payum/Core/Registry/SimpleRegistry.php:37)
  at Payum\Core\Registry\SimpleRegistry->getGateway('bitbag_imoje')
     (vendor/payum/payum/src/Payum/Core/Registry/FallbackRegistry.php:56)
  at Payum\Core\Registry\FallbackRegistry->getGateway('bitbag_imoje')
     (vendor/payum/payum/src/Payum/Core/Registry/FallbackRegistry.php:56)
  at Payum\Core\Registry\FallbackRegistry->getGateway('bitbag_imoje')
     (vendor/payum/payum/src/Payum/Core/Payum.php:70)
  at Payum\Core\Payum->getGateway('bitbag_imoje')
     (vendor/payum/payum-bundle/Controller/CaptureController.php:42)
  at Payum\Bundle\PayumBundle\Controller\CaptureController->doAction(object(Request))
     (vendor/symfony/http-kernel/HttpKernel.php:163)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:75)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:25)
```
 
I've tried changing code to "ing" or "imoje" but it didn't work. How to register this gateway? I suppose this should be automatically.

Command ```php bin/console debug:config payum``` gives this result:
```
payum:
    storages:
        App\Entity\Order\Order:
            doctrine:
                driver: orm
            extension:
                all: true
                gateways: {  }
                factories: {  }
        App\Entity\Payment\Payment:
            doctrine:
                driver: orm
            extension:
                all: true
                gateways: {  }
                factories: {  }
    security:
        token_storage:
            Sylius\Bundle\PayumBundle\Model\PaymentSecurityToken:
                doctrine:
                    driver: orm
    dynamic_gateways:
        config_storage:
            Sylius\Bundle\PayumBundle\Model\GatewayConfig:
                doctrine:
                    driver: orm
        sonata_admin: false
    gateways:
        offline:
            factory: offline
```
```sylius_gateway_config table:```
![image](https://user-images.githubusercontent.com/70874987/220874363-27708250-c4ee-43c2-8fb9-ecfe82f4b98a.png)
```sylius_payment_method table:```
![image](https://user-images.githubusercontent.com/70874987/220874674-7a8d147e-d0e3-4510-a5ac-cfe973682f77.png)

Of course, I tried other payment method names and their code such as "ing", "testing", "imoje". Only in the example above the names are the same as the factory name.

Your plugin Przelewy24 works fine. I don't have any idea what's going on.
